Southern Africa IPC Map
OCHA-DAP/pa-rosea-support pull request #2
Opened 2023-12-20 06:17 UTC by PaulineNimo

R Script to create some IPC maps for Total at risk and % of Population

2023-12-20 14:14 UTC, zackarno reviewed
Nice work, very cool maps! Just some minor comments above, but otherwise LGTM!

2023-12-20 14:14 UTC, zackarno commented on drought/southern-africa/drought_impact_2023.Rmd
> +title: "Untitled"
title?

2023-12-20 14:14 UTC, zackarno commented on drought/southern-africa/drought_impact_2023.Rmd
> +esa_shp <- st_read("C:/Users/pauni/Desktop/Work/OCHA/ROSEA/esa_admin1_region/ESA_admin1_region.shp")
To run I need to change path to:

```
# reading in data
shp_path <- file.path(
  Sys.getenv("AA_DATA_DIR"), 
  "public", "raw", "esa", "cod_ab", 
  "esa_admin1_region", "ESA_admin1_region.shp")
esa_shp <- st_read(shp_path)
```

2023-12-20 14:14 UTC, zackarno commented on drought/southern-africa/southern_africa_ipc_map.R
> +load_source_sans_3()
curious why this is better than `{ripc}` like you used in the `.Rmd`

2023-12-20 14:14 UTC, zackarno commented on drought/southern-africa/southern_africa_ipc_map.R
> +            subtitle = "Population at Risk in '00,000s") +
"Population at Risk in '00,000s" -- maybe this is a standard way to present these figures, but in my IMO it might not be super clear to our audience.

What could be more clear would be 1.  leave the number as is (not divide by 100,000) , 2. change plot subtitle to "Population at risk" , c. change legend breaks to read c("0","200k","400k","600k")

2023-12-20 14:14 UTC, zackarno commented on drought/southern-africa/southern_africa_ipc_map.R
> +  phase3 <- geodata1 %>%
might want rename `phase3` to something more generic since fn allows user to change phase?

2023-12-20 14:14 UTC, zackarno commented on drought/southern-africa/southern_africa_ipc_map.R
> +    scale_fill_gradient(low="pink", high="red") +
could could consider `label= scales::label_percent()`, also could potentially flip color ramp labels 90 degree  so they are easier to read on a couple?

2023-12-21 11:54 UTC, caldwellst requested changes
Similar comments to Zack's, but is looking really nice! I like the shiny app approach.

2023-12-21 11:54 UTC, caldwellst commented on drought/southern-africa/drought_impact_2023.Rmd
> +load_source_sans_3()
You can just use `gghdx()` to set all of these automatically.

2023-12-21 11:54 UTC, caldwellst commented on drought/southern-africa/drought_impact_2023.Rmd
> +      labs(fill = "in '00,000s") +
I think it's 100,000s?

2023-12-21 11:54 UTC, caldwellst commented on drought/southern-africa/drought_impact_2023.Rmd
> +esa_iso2 <- c("AO", "SZ", "LS", "MG", "MW", "MZ", "NA", "MW", "MZ", "ZA", "ZM", "ZW")
Botswana? I find it strange that Botswana is missing in white, while others included but no IPC data are dark grey. Maybe put all countries with no IPC data as white?

2023-12-21 11:54 UTC, caldwellst commented on drought/southern-africa/southern_africa_ipc_map.R
> +            subtitle = "Population at Risk in '00,000s") +
Yeah, had the same thoughts, good points.

2023-12-21 11:54 UTC, caldwellst commented on drought/southern-africa/drought_impact_2023.Rmd
> +      labs(fill = "in '00,000s") +
Oh that's what this is, just got confused by the 00,000s without the 1. Agree with Zack's comments about clarity in this presentation.

2023-12-21 11:54 UTC, caldwellst commented on drought/southern-africa/drought_impact_2023.Rmd
> +      ggtitle(label = paste("Acute Food Insecurity IPC ", input$ipc_phases), subtitle = "Population at Risk Oct 2023 - Mar 2024 in '00,000s") +
I guess should just make sure people are aware these timelines vary by country?

2023-12-21 12:51 UTC, PaulineNimo commented
Thanks both! Will look through tonight.

2024-01-02 11:01 UTC, PaulineNimo commented on drought/southern-africa/southern_africa_ipc_map.R
> +load_source_sans_3()
I tried to look for subnational data via ripc but just ended up going with the data on HDX.

2024-01-02 11:05 UTC, PaulineNimo commented on drought/southern-africa/drought_impact_2023.Rmd
> +      ggtitle(label = paste("Acute Food Insecurity IPC ", input$ipc_phases), subtitle = "Population at Risk Oct 2023 - Mar 2024 in '00,000s") +
yeah, have added some text to the plots

2024-01-02 13:48 UTC, caldwellst approved these changes

2024-01-02 17:41 UTC, merged